server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost/edu?characterEncoding=utf-8&useSSL=false
  rabbitmq:
    host: localhost

# edu数据模块配置
edu:
  data:
    max-data-size: 2000000
    data-path: C:\Users\Administrator\Desktop\edu-backend\data-cache

