spring:
  profiles:
    active: dev
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
fast-redis:
  use-default-redisTemplate: true


# 配置扫描xml
mybatis-plus:
  mapper-locations=classpath: mapper/*.xml
  # 实体扫描，多个package用逗号或者分号分隔
  type-aliases-package: com.njupt.hpc.edu.*.model

# jwt
jwt:
  secret: njput_bigdataEdu_hpc_molamola
#  十个小时过期
  expiration: 36000
  tokenHeader: Authorization
  tokenHead: Bearer


